networks:
  zabbix-net:
    name: zabbix-net
    external: true

services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_METADATA: "docker-study"
    ports:
      - "10050:10050"
    networks:
      - zabbix-net
    privileged: true
    pid: "host"
    restart: unless-stopped
